"""Beacon API /eth/v1/config/spec endpoint builder."""

from ..spec.network_config import get_config as get_network_config
from ..spec import constants
from .utils import to_hex


def build_spec_response() -> dict:
    """Build the spec response for GET /eth/v1/config/spec."""
    net_config = get_network_config()
    preset = constants.get_preset()

    spec = {
        # Config values (from network config)
        "CONFIG_NAME": net_config.config_name,
        "PRESET_BASE": preset,
        "TERMINAL_TOTAL_DIFFICULTY": str(net_config.terminal_total_difficulty),
        "TERMINAL_BLOCK_HASH": to_hex(net_config.terminal_block_hash, 32),
        "TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH": str(net_config.terminal_block_hash_activation_epoch),
        "MIN_GENESIS_ACTIVE_VALIDATOR_COUNT": str(net_config.min_genesis_active_validator_count),
        "MIN_GENESIS_TIME": str(net_config.min_genesis_time),
        "GENESIS_FORK_VERSION": to_hex(net_config.genesis_fork_version, 4),
        "GENESIS_DELAY": str(net_config.genesis_delay),
        "ALTAIR_FORK_VERSION": to_hex(net_config.altair_fork_version, 4),
        "ALTAIR_FORK_EPOCH": str(net_config.altair_fork_epoch),
        "BELLATRIX_FORK_VERSION": to_hex(net_config.bellatrix_fork_version, 4),
        "BELLATRIX_FORK_EPOCH": str(net_config.bellatrix_fork_epoch),
        "CAPELLA_FORK_VERSION": to_hex(net_config.capella_fork_version, 4),
        "CAPELLA_FORK_EPOCH": str(net_config.capella_fork_epoch),
        "DENEB_FORK_VERSION": to_hex(net_config.deneb_fork_version, 4),
        "DENEB_FORK_EPOCH": str(net_config.deneb_fork_epoch),
        "ELECTRA_FORK_VERSION": to_hex(net_config.electra_fork_version, 4),
        "ELECTRA_FORK_EPOCH": str(net_config.electra_fork_epoch),
        "FULU_FORK_VERSION": to_hex(net_config.fulu_fork_version, 4),
        "FULU_FORK_EPOCH": str(net_config.fulu_fork_epoch),
        "GLOAS_FORK_VERSION": to_hex(net_config.gloas_fork_version, 4),
        "GLOAS_FORK_EPOCH": str(net_config.gloas_fork_epoch),
        "SLOT_DURATION_MS": str(net_config.slot_duration_ms),
        "SECONDS_PER_SLOT": str(net_config.slot_duration_ms // 1000),
        "SECONDS_PER_ETH1_BLOCK": str(net_config.seconds_per_eth1_block),
        "MIN_VALIDATOR_WITHDRAWABILITY_DELAY": str(net_config.min_validator_withdrawability_delay),
        "SHARD_COMMITTEE_PERIOD": str(net_config.shard_committee_period),
        "ETH1_FOLLOW_DISTANCE": str(net_config.eth1_follow_distance),
        "INACTIVITY_SCORE_BIAS": str(net_config.inactivity_score_bias),
        "INACTIVITY_SCORE_RECOVERY_RATE": str(net_config.inactivity_score_recovery_rate),
        "EJECTION_BALANCE": str(net_config.ejection_balance),
        "MIN_PER_EPOCH_CHURN_LIMIT": str(net_config.min_per_epoch_churn_limit),
        "CHURN_LIMIT_QUOTIENT": str(net_config.churn_limit_quotient),
        "PROPOSER_SCORE_BOOST": str(net_config.proposer_score_boost),
        "DEPOSIT_CHAIN_ID": str(net_config.deposit_chain_id),
        "DEPOSIT_NETWORK_ID": str(net_config.deposit_network_id),
        "DEPOSIT_CONTRACT_ADDRESS": to_hex(net_config.deposit_contract_address, 20),
        # Phase 0 preset constants
        "MAX_COMMITTEES_PER_SLOT": str(constants.MAX_COMMITTEES_PER_SLOT()),
        "TARGET_COMMITTEE_SIZE": str(constants.TARGET_COMMITTEE_SIZE()),
        "MAX_VALIDATORS_PER_COMMITTEE": str(constants.MAX_VALIDATORS_PER_COMMITTEE()),
        "SHUFFLE_ROUND_COUNT": str(constants.SHUFFLE_ROUND_COUNT()),
        "HYSTERESIS_QUOTIENT": str(constants.HYSTERESIS_QUOTIENT),
        "HYSTERESIS_DOWNWARD_MULTIPLIER": str(constants.HYSTERESIS_DOWNWARD_MULTIPLIER),
        "HYSTERESIS_UPWARD_MULTIPLIER": str(constants.HYSTERESIS_UPWARD_MULTIPLIER),
        "MIN_DEPOSIT_AMOUNT": str(constants.MIN_DEPOSIT_AMOUNT),
        "MAX_EFFECTIVE_BALANCE": str(constants.MAX_EFFECTIVE_BALANCE),
        "EFFECTIVE_BALANCE_INCREMENT": str(constants.EFFECTIVE_BALANCE_INCREMENT),
        "MIN_ATTESTATION_INCLUSION_DELAY": str(constants.MIN_ATTESTATION_INCLUSION_DELAY),
        "SLOTS_PER_EPOCH": str(constants.SLOTS_PER_EPOCH()),
        "MIN_SEED_LOOKAHEAD": str(constants.MIN_SEED_LOOKAHEAD),
        "MAX_SEED_LOOKAHEAD": str(constants.MAX_SEED_LOOKAHEAD),
        "EPOCHS_PER_ETH1_VOTING_PERIOD": str(constants.EPOCHS_PER_ETH1_VOTING_PERIOD()),
        "SLOTS_PER_HISTORICAL_ROOT": str(constants.SLOTS_PER_HISTORICAL_ROOT()),
        "MIN_EPOCHS_TO_INACTIVITY_PENALTY": str(constants.MIN_EPOCHS_TO_INACTIVITY_PENALTY),
        "EPOCHS_PER_HISTORICAL_VECTOR": str(constants.EPOCHS_PER_HISTORICAL_VECTOR()),
        "EPOCHS_PER_SLASHINGS_VECTOR": str(constants.EPOCHS_PER_SLASHINGS_VECTOR()),
        "HISTORICAL_ROOTS_LIMIT": str(constants.HISTORICAL_ROOTS_LIMIT),
        "VALIDATOR_REGISTRY_LIMIT": str(constants.VALIDATOR_REGISTRY_LIMIT),
        "BASE_REWARD_FACTOR": str(constants.BASE_REWARD_FACTOR),
        "WHISTLEBLOWER_REWARD_QUOTIENT": str(constants.WHISTLEBLOWER_REWARD_QUOTIENT),
        "PROPOSER_REWARD_QUOTIENT": str(constants.PROPOSER_REWARD_QUOTIENT),
        "INACTIVITY_PENALTY_QUOTIENT": str(constants.INACTIVITY_PENALTY_QUOTIENT()),
        "MIN_SLASHING_PENALTY_QUOTIENT": str(constants.MIN_SLASHING_PENALTY_QUOTIENT()),
        "PROPORTIONAL_SLASHING_MULTIPLIER": str(constants.PROPORTIONAL_SLASHING_MULTIPLIER()),
        "MAX_PROPOSER_SLASHINGS": str(constants.MAX_PROPOSER_SLASHINGS),
        "MAX_ATTESTER_SLASHINGS": str(constants.MAX_ATTESTER_SLASHINGS),
        "MAX_ATTESTATIONS": str(constants.MAX_ATTESTATIONS()),
        "MAX_DEPOSITS": str(constants.MAX_DEPOSITS),
        "MAX_VOLUNTARY_EXITS": str(constants.MAX_VOLUNTARY_EXITS),
        # Altair
        "SYNC_COMMITTEE_SIZE": str(constants.SYNC_COMMITTEE_SIZE()),
        "EPOCHS_PER_SYNC_COMMITTEE_PERIOD": str(constants.EPOCHS_PER_SYNC_COMMITTEE_PERIOD()),
        "MIN_SYNC_COMMITTEE_PARTICIPANTS": str(constants.MIN_SYNC_COMMITTEE_PARTICIPANTS),
        "UPDATE_TIMEOUT": str(constants.UPDATE_TIMEOUT),
        "INACTIVITY_PENALTY_QUOTIENT_ALTAIR": str(constants.INACTIVITY_PENALTY_QUOTIENT_ALTAIR),
        "MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR": str(constants.MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR),
        "PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR": str(constants.PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR),
        # Bellatrix
        "BYTES_PER_LOGS_BLOOM": str(constants.BYTES_PER_LOGS_BLOOM),
        "MAX_EXTRA_DATA_BYTES": str(constants.MAX_EXTRA_DATA_BYTES),
        "MAX_BYTES_PER_TRANSACTION": str(constants.MAX_BYTES_PER_TRANSACTION),
        "MAX_TRANSACTIONS_PER_PAYLOAD": str(constants.MAX_TRANSACTIONS_PER_PAYLOAD),
        "INACTIVITY_PENALTY_QUOTIENT_BELLATRIX": str(constants.INACTIVITY_PENALTY_QUOTIENT_BELLATRIX),
        "MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX": str(constants.MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX),
        "PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX": str(constants.PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX),
        # Capella
        "MAX_BLS_TO_EXECUTION_CHANGES": str(constants.MAX_BLS_TO_EXECUTION_CHANGES),
        "MAX_WITHDRAWALS_PER_PAYLOAD": str(constants.MAX_WITHDRAWALS_PER_PAYLOAD()),
        "MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP": str(constants.MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP()),
        # Deneb
        "MAX_BLOB_COMMITMENTS_PER_BLOCK": str(constants.MAX_BLOB_COMMITMENTS_PER_BLOCK),
        "FIELD_ELEMENTS_PER_BLOB": str(constants.FIELD_ELEMENTS_PER_BLOB),
        "KZG_COMMITMENT_INCLUSION_PROOF_DEPTH": str(constants.KZG_COMMITMENT_INCLUSION_PROOF_DEPTH),
        "MAX_BLOBS_PER_BLOCK": str(constants.MAX_BLOBS_PER_BLOCK),
        "MAX_REQUEST_BLOCKS_DENEB": str(constants.MAX_REQUEST_BLOCKS_DENEB),
        "MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS": str(constants.MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS),
        "BLOB_SIDECAR_SUBNET_COUNT": str(constants.BLOB_SIDECAR_SUBNET_COUNT),
        "MAX_REQUEST_BLOB_SIDECARS": str(constants.MAX_REQUEST_BLOB_SIDECARS),
        # Electra
        "MIN_ACTIVATION_BALANCE": str(constants.MIN_ACTIVATION_BALANCE),
        "MAX_EFFECTIVE_BALANCE_ELECTRA": str(constants.MAX_EFFECTIVE_BALANCE_ELECTRA),
        "MIN_SLASHING_PENALTY_QUOTIENT_ELECTRA": str(constants.MIN_SLASHING_PENALTY_QUOTIENT_ELECTRA),
        "WHISTLEBLOWER_REWARD_QUOTIENT_ELECTRA": str(constants.WHISTLEBLOWER_REWARD_QUOTIENT_ELECTRA),
        "PENDING_DEPOSITS_LIMIT": str(constants.PENDING_DEPOSITS_LIMIT()),
        "PENDING_PARTIAL_WITHDRAWALS_LIMIT": str(constants.PENDING_PARTIAL_WITHDRAWALS_LIMIT()),
        "PENDING_CONSOLIDATIONS_LIMIT": str(constants.PENDING_CONSOLIDATIONS_LIMIT()),
        "MAX_ATTESTER_SLASHINGS_ELECTRA": str(constants.MAX_ATTESTER_SLASHINGS_ELECTRA),
        "MAX_ATTESTATIONS_ELECTRA": str(constants.MAX_ATTESTATIONS_ELECTRA()),
        "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD": str(constants.MAX_DEPOSIT_REQUESTS_PER_PAYLOAD),
        "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD": str(constants.MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD),
        "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD": str(constants.MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD),
        "MAX_PENDING_PARTIALS_PER_WITHDRAWALS_SWEEP": str(constants.MAX_PENDING_PARTIALS_PER_WITHDRAWALS_SWEEP()),
        "MAX_PENDING_DEPOSITS_PER_EPOCH": str(constants.MAX_PENDING_DEPOSITS_PER_EPOCH),
        "KZG_COMMITMENTS_INCLUSION_PROOF_DEPTH": str(constants.KZG_COMMITMENTS_INCLUSION_PROOF_DEPTH_ELECTRA),
        "MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA": str(constants.MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA()),
        "MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT": str(constants.MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT()),
        "MAX_BLOBS_PER_BLOCK_ELECTRA": str(constants.MAX_BLOBS_PER_BLOCK_ELECTRA),
        "BLOB_SIDECAR_SUBNET_COUNT_ELECTRA": str(constants.BLOB_SIDECAR_SUBNET_COUNT_ELECTRA),
        "MAX_REQUEST_BLOB_SIDECARS_ELECTRA": str(constants.MAX_REQUEST_BLOB_SIDECARS_ELECTRA),
        # Fulu (PeerDAS)
        "FIELD_ELEMENTS_PER_CELL": str(constants.FIELD_ELEMENTS_PER_CELL),
        "FIELD_ELEMENTS_PER_EXT_BLOB": str(constants.FIELD_ELEMENTS_PER_EXT_BLOB),
        "CELLS_PER_EXT_BLOB": str(constants.CELLS_PER_EXT_BLOB),
        "NUMBER_OF_COLUMNS": str(constants.NUMBER_OF_COLUMNS),
        "NUMBER_OF_CUSTODY_GROUPS": str(constants.NUMBER_OF_CUSTODY_GROUPS),
        "DATA_COLUMN_SIDECAR_SUBNET_COUNT": str(constants.DATA_COLUMN_SIDECAR_SUBNET_COUNT),
        "MAX_REQUEST_DATA_COLUMN_SIDECARS": str(constants.MAX_REQUEST_DATA_COLUMN_SIDECARS),
        "SAMPLES_PER_SLOT": str(constants.SAMPLES_PER_SLOT),
        "CUSTODY_REQUIREMENT": str(constants.CUSTODY_REQUIREMENT),
        "VALIDATOR_CUSTODY_REQUIREMENT": str(constants.VALIDATOR_CUSTODY_REQUIREMENT),
        "BALANCE_PER_ADDITIONAL_CUSTODY_GROUP": str(constants.BALANCE_PER_ADDITIONAL_CUSTODY_GROUP),
        "MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS": str(constants.MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS),
        # Gloas (ePBS)
        "PTC_SIZE": str(constants.PTC_SIZE()),
        "MAX_PAYLOAD_ATTESTATIONS": str(constants.MAX_PAYLOAD_ATTESTATIONS),
        # Networking constants
        "MAX_PAYLOAD_SIZE": str(constants.MAX_PAYLOAD_SIZE),
        "MAX_REQUEST_BLOCKS": str(constants.MAX_REQUEST_BLOCKS),
        "EPOCHS_PER_SUBNET_SUBSCRIPTION": str(constants.EPOCHS_PER_SUBNET_SUBSCRIPTION),
        "MIN_EPOCHS_FOR_BLOCK_REQUESTS": str(constants.MIN_EPOCHS_FOR_BLOCK_REQUESTS()),
        "ATTESTATION_PROPAGATION_SLOT_RANGE": str(constants.ATTESTATION_PROPAGATION_SLOT_RANGE),
        "MAXIMUM_GOSSIP_CLOCK_DISPARITY": str(constants.MAXIMUM_GOSSIP_CLOCK_DISPARITY),
        "MESSAGE_DOMAIN_INVALID_SNAPPY": "0x" + constants.MESSAGE_DOMAIN_INVALID_SNAPPY.hex(),
        "MESSAGE_DOMAIN_VALID_SNAPPY": "0x" + constants.MESSAGE_DOMAIN_VALID_SNAPPY.hex(),
        "SUBNETS_PER_NODE": str(constants.SUBNETS_PER_NODE),
        "ATTESTATION_SUBNET_COUNT": str(constants.ATTESTATION_SUBNET_COUNT),
        "ATTESTATION_SUBNET_EXTRA_BITS": str(constants.ATTESTATION_SUBNET_EXTRA_BITS),
        "ATTESTATION_SUBNET_PREFIX_BITS": str(constants.ATTESTATION_SUBNET_PREFIX_BITS),
        "MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT": str(constants.MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT()),
        "REORG_HEAD_WEIGHT_THRESHOLD": str(constants.REORG_HEAD_WEIGHT_THRESHOLD()),
        "REORG_PARENT_WEIGHT_THRESHOLD": str(constants.REORG_PARENT_WEIGHT_THRESHOLD()),
        "REORG_MAX_EPOCHS_SINCE_FINALIZATION": str(constants.REORG_MAX_EPOCHS_SINCE_FINALIZATION()),
        # Domain types (withdrawal prefixes are single-byte integers)
        "BLS_WITHDRAWAL_PREFIX": f"0x{constants.BLS_WITHDRAWAL_PREFIX:02x}",
        "ETH1_ADDRESS_WITHDRAWAL_PREFIX": f"0x{constants.ETH1_ADDRESS_WITHDRAWAL_PREFIX:02x}",
        "COMPOUNDING_WITHDRAWAL_PREFIX": f"0x{constants.COMPOUNDING_WITHDRAWAL_PREFIX:02x}",
        "DOMAIN_BEACON_PROPOSER": "0x" + constants.DOMAIN_BEACON_PROPOSER.hex(),
        "DOMAIN_BEACON_ATTESTER": "0x" + constants.DOMAIN_BEACON_ATTESTER.hex(),
        "DOMAIN_RANDAO": "0x" + constants.DOMAIN_RANDAO.hex(),
        "DOMAIN_DEPOSIT": "0x" + constants.DOMAIN_DEPOSIT.hex(),
        "DOMAIN_VOLUNTARY_EXIT": "0x" + constants.DOMAIN_VOLUNTARY_EXIT.hex(),
        "DOMAIN_SELECTION_PROOF": "0x" + constants.DOMAIN_SELECTION_PROOF.hex(),
        "DOMAIN_AGGREGATE_AND_PROOF": "0x" + constants.DOMAIN_AGGREGATE_AND_PROOF.hex(),
        "DOMAIN_SYNC_COMMITTEE": "0x" + constants.DOMAIN_SYNC_COMMITTEE.hex(),
        "DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF": "0x" + constants.DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF.hex(),
        "DOMAIN_CONTRIBUTION_AND_PROOF": "0x" + constants.DOMAIN_CONTRIBUTION_AND_PROOF.hex(),
        "DOMAIN_BLS_TO_EXECUTION_CHANGE": "0x" + constants.DOMAIN_BLS_TO_EXECUTION_CHANGE.hex(),
        "TARGET_AGGREGATORS_PER_COMMITTEE": str(constants.TARGET_AGGREGATORS_PER_COMMITTEE),
        "TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE": str(constants.TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE),
        "SYNC_COMMITTEE_SUBNET_COUNT": str(constants.SYNC_COMMITTEE_SUBNET_COUNT),
    }

    if net_config.blob_schedule:
        spec["BLOB_SCHEDULE"] = [
            {k.upper(): str(v) for k, v in entry.items()}
            for entry in net_config.blob_schedule
        ]

    return spec
