"""Helper functions for state transition."""

from .math import integer_squareroot, xor, saturating_sub
from .misc import (
    compute_epoch_at_slot,
    compute_start_slot_at_epoch,
    compute_activation_exit_epoch,
    compute_fork_data_root,
    compute_fork_digest,
    convert_builder_index_to_validator_index,
    convert_validator_index_to_builder_index,
)
from .predicates import (
    is_active_validator,
    is_eligible_for_activation_queue,
    is_eligible_for_activation,
    is_slashable_validator,
    is_slashable_attestation_data,
    is_valid_indexed_attestation,
    is_valid_merkle_branch,
    is_merge_transition_complete,
    is_execution_enabled,
    has_eth1_withdrawal_credential,
    is_fully_withdrawable_validator,
    is_partially_withdrawable_validator,
    is_compounding_withdrawal_credential,
    has_compounding_withdrawal_credential,
    has_execution_withdrawal_credential,
    is_valid_switch_to_compounding_request,
    is_builder_index,
    is_active_builder,
    is_builder_withdrawal_credential,
    is_valid_indexed_payload_attestation,
)
from .accessors import (
    get_current_epoch,
    get_previous_epoch,
    get_block_root,
    get_block_root_at_slot,
    get_randao_mix,
    get_active_validator_indices,
    get_validator_churn_limit,
    get_balance_churn_limit,
    get_activation_exit_churn_limit,
    get_consolidation_churn_limit,
    get_seed,
    get_total_balance,
    get_total_active_balance,
    get_base_reward_per_increment,
    get_base_reward,
    get_proposer_reward,
    get_finality_delay,
    is_in_inactivity_leak,
    get_eligible_validator_indices,
    get_max_effective_balance,
    get_pending_balance_to_withdraw,
    get_pending_balance_to_withdraw_for_builder,
    can_builder_cover_bid,
)
from .mutators import (
    increase_balance,
    decrease_balance,
    initiate_validator_exit,
    slash_validator,
    switch_to_compounding_validator,
    queue_excess_active_balance,
    compute_exit_epoch_and_update_churn,
    compute_consolidation_epoch_and_update_churn,
)
from .beacon_committee import (
    compute_shuffled_index,
    compute_proposer_index,
    compute_committee,
    get_committee_count_per_slot,
    get_beacon_committee,
    get_beacon_proposer_index,
)
from .domain import (
    get_domain,
    compute_domain,
    compute_signing_root,
)
from .attestation import (
    get_attesting_indices,
    get_indexed_attestation,
    get_attestation_participation_flag_indices,
    get_unslashed_participating_indices,
    add_flag,
    has_flag,
    get_committee_indices,
    is_attestation_same_slot,
)
from .ptc import (
    get_ptc,
    get_ptc_slot,
    is_ptc_member,
    get_indexed_payload_attestation,
)

__all__ = [
    # Math
    "integer_squareroot",
    "xor",
    "saturating_sub",
    # Misc
    "compute_epoch_at_slot",
    "compute_start_slot_at_epoch",
    "compute_activation_exit_epoch",
    "compute_fork_data_root",
    "compute_fork_digest",
    "convert_builder_index_to_validator_index",
    "convert_validator_index_to_builder_index",
    # Predicates
    "is_active_validator",
    "is_eligible_for_activation_queue",
    "is_eligible_for_activation",
    "is_slashable_validator",
    "is_slashable_attestation_data",
    "is_valid_indexed_attestation",
    "is_valid_merkle_branch",
    "is_merge_transition_complete",
    "is_execution_enabled",
    "has_eth1_withdrawal_credential",
    "is_fully_withdrawable_validator",
    "is_partially_withdrawable_validator",
    "is_compounding_withdrawal_credential",
    "has_compounding_withdrawal_credential",
    "has_execution_withdrawal_credential",
    "is_builder_index",
    "is_active_builder",
    "is_builder_withdrawal_credential",
    "is_valid_indexed_payload_attestation",
    # Accessors
    "get_current_epoch",
    "get_previous_epoch",
    "get_block_root",
    "get_block_root_at_slot",
    "get_randao_mix",
    "get_active_validator_indices",
    "get_validator_churn_limit",
    "get_balance_churn_limit",
    "get_activation_exit_churn_limit",
    "get_consolidation_churn_limit",
    "get_seed",
    "get_total_balance",
    "get_total_active_balance",
    "get_base_reward_per_increment",
    "get_base_reward",
    "get_proposer_reward",
    "get_finality_delay",
    "is_in_inactivity_leak",
    "get_eligible_validator_indices",
    "get_max_effective_balance",
    "get_pending_balance_to_withdraw",
    "get_pending_balance_to_withdraw_for_builder",
    "can_builder_cover_bid",
    # Mutators
    "increase_balance",
    "decrease_balance",
    "initiate_validator_exit",
    "slash_validator",
    "switch_to_compounding_validator",
    "queue_excess_active_balance",
    "compute_exit_epoch_and_update_churn",
    "compute_consolidation_epoch_and_update_churn",
    # Beacon committee
    "compute_shuffled_index",
    "compute_proposer_index",
    "compute_committee",
    "get_committee_count_per_slot",
    "get_beacon_committee",
    "get_beacon_proposer_index",
    # Domain
    "get_domain",
    "compute_domain",
    "compute_signing_root",
    # Attestation
    "get_attesting_indices",
    "get_indexed_attestation",
    "get_attestation_participation_flag_indices",
    "get_unslashed_participating_indices",
    "add_flag",
    "has_flag",
    "get_committee_indices",
    "is_attestation_same_slot",
    # PTC (Gloas/ePBS)
    "get_ptc",
    "get_ptc_slot",
    "is_ptc_member",
    "get_indexed_payload_attestation",
]
